config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, only: [:create, :update, :edit, :destroy, :show]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer          not null
#  live       :boolean          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :year, :live, presence: true

  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Band
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Album
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token
  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = self.find_by(email: email)

    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :login_redirect

  def login_redirect
    unless logged_in?
      redirect_to new_session_url
    end
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    if @album
      render :edit
    else
      flash[:errors] = ['Album not found!']
      redirect_to bands_url
    end
  end

  def update
    debugger
    @album = Album.find_by(id: params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])

    if @album
      @album.destroy
      redirect_to bands_url
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to bands_url
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :title, :year, :live)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :login_redirect

  def login_redirect
    unless logged_in?
      redirect_to new_session_url
    end
  end

  def index
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band
      render :show
    else
      flash[:errors] = ['Band not found!']
      redirect_to bands_url
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    if @band
      render :edit
    else
      flash[:errors] = ['Band not found!']
      redirect_to bands_url
    end
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])

    if @band
      @band.destroy
      redirect_to bands_url
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to bands_url
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :login_redirect, only: [:new, :create]

  def login_redirect
    if logged_in?
      redirect_to user_url(@user)
    end
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Email or password invalid"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_redirect, only: [:new, :create]

  def login_redirect
    if logged_in?
      redirect_to user_url(@user)
    end
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(session_token: session[:session_token])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<% if type == :new %>
  <% action_url = albums_url %>
  <% button_val = "Record that record!"%>
<% elsif type == :edit %>
  <%  action_url = album_url(album)%>
  <%  button_val = "Remaster"%>
<% end%>

<form action="<%= action_url%>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <%end%>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">

  <select name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value="<%=band.id %>"><%= band.name%></option>
    <% end %>
  </select>
  <br>

  <label class="prompt">Title:
    <input type="text" name="album[title]" value="<%= album.title%>">
  </label>
  <br>

  <label class="prompt">Year:
    <input type="text" name="album[year]" value="<%= album.year%>">
  </label>
  <br>

  <label class="prompt">Recorded Live?

  <input type="radio" id="liveyes?" name="album[live]" value="t"
  <%= album.live ? "checked" : ""%>>
  <label for="liveyes?">Yes</label>

  <input type="radio" id="liveno?" name="album[live]" value="f"
  <%= album.live == false ? "checked" : ""%>>
  <label for="liveno?">No</label>

  </label>

  <br>
  <input type="submit" value="<%= button_val%>"">
</form>

app/views/albums/edit.html.erb
<h2>Audacity</h2>

<%= render 'form', album: @album, type: :edit%>

app/views/albums/new.html.erb
<h3>Add an album</h3>

<%= render 'form', album: @album, type: :new%>

app/views/albums/show.html.erb
<h2><a href="<%= band_url(@album.band)%>"><%= @album.band.name%></a> 's <%= @album.title%></h2>

<body>
    <form action="<%= album_url(@album)%>" method="post">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
      <input type="submit" value="*record scratch*">
    </form>
    <br>
    <a class="links" href="<%= edit_album_url(@album)%>">Needs a remaster?</a>
</body>

app/views/bands/_form.html.erb
<% if type == :new %>
  <% action_url = bands_url %>
  <%  button_val = "Add your jams!"%>
<% elsif type == :edit %>
  <%  action_url = band_url(band)%>
  <%  button_val = "Change your beats!"%>
<% end%>

<form action="<%= action_url%>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <%end%>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">

  <label class="prompt">Band name:
  <input type="text" name="band[name]" value="<%= band.name%>">
</label>
  <br>
  <input type="submit" value="<%= button_val%>"">
</form>

app/views/bands/edit.html.erb
<h2><%= current_user.email%>, here to change it up?</h2>
<h3>Edit your band</h3>

<%= render 'form', band: @band, type: :edit%>

app/views/bands/index.html.erb
<h2><%= current_user.email%> was BAND for this post!</h2>

<body>
  <ul><% Band.all.each do |band|%>
    <li><a href="<%= band_url(band)%>"><%= band.name %></a></li>
    <form action="<%= band_url(band)%>" method="post">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
      <input type="submit" value="Disband">
    </form>
  <% end%>
  </ul>
</body>

app/views/bands/new.html.erb
<h2><%= current_user.email%>, become a rockstar!</h2>
<h3>Add your band</h3>

<%= render 'form', band: @band, type: :new%>

app/views/bands/show.html.erb
<h2><%= @band.name%> 's jams</h2>

<body>
  <ul>
      <% @band.albums.each do |album| %>
      <a href="<%= album_url(album.id)%>"><%= album.title%></a>
      <%end%>
  </ul>
  <a href="<%= new_band_album_url(@band)%>">New record?</a>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <header>
      <p class="header text_shadow">Music App</p>
      <nav>
        <% if logged_in? %>
          <h3> Yo, <%= current_user.email%></h3>
          <form action="<%= session_url%>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Make like a tree and logout">
          </form>
        <% else%>
          <a class="navlinks" href="<%= new_session_url%>">Log in to your bass</a><br>
          <a class="navlinks" href="<%=new_user_url%>">Make some treble</a>
        <% end%>
      </nav>
    </header>
  </head>

  <body>



    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
      <li><%= error  %></li>
      <% end%>
    <% end%>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if type == :new %>
  <%  action_url = users_url %>
  <%  button_val = "Musical Journey START!"%>
<% elsif type == :login %>
  <%  action_url = session_url%>
  <%  button_val = "Show me your moves!"%>
<% end%>


<form class="user" action="<%= action_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
  <label class="prompt">E-mail:
    <input class="user_input" type="email" name="user[email]" value="">
  </label>
  <br>

  <label class="prompt">Password:
    <input class="user_input" type="password" name="user[password]" value="">
  </label>
  <br>
  <input class="user_input" type="submit" value="<%= button_val  %>">
</form>

app/views/users/new.html.erb
<h2 class="prompt">Sign up to drop some beats</h2>

<%= render 'form', user: @user, type: :new %>

app/views/users/show.html.erb
<h2>It's YOU!</h2>

<h3><%= current_user.email%></h3>